"""add reviews.py

Revision ID: 2e5fe6573051
Revises: 95c08d2ab178
Create Date: 2024-01-24 22:22:33.479672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5fe6573051'
down_revision: Union[str, None] = '95c08d2ab178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('score', sa.Integer(), nullable=True),
                    sa.Column('message', sa.String(), nullable=True),
                    sa.Column('for_role', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('reviewer_id', sa.Integer(), nullable=True),
                    sa.Column('reviewee_id', sa.Integer(), nullable=True),
                    sa.Column('sitter_profile_id',
                              sa.Integer(), nullable=True),
                    sa.Column('booking_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
                    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['sitter_profile_id'], [
                        'sitterprofiles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.alter_column('users', 'role',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
