"""add a column userid

Revision ID: 4811b440f0f4
Revises: 369201a0b319
Create Date: 2024-01-18 17:05:14.998595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4811b440f0f4'
down_revision: Union[str, None] = '369201a0b319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sitterprofiles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sitterprofiles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sitterprofiles', type_='foreignkey')
    op.drop_column('sitterprofiles', 'user_id')
    # ### end Alembic commands ###
