"""add_bookings.py

Revision ID: c73df300922c
Revises: e6f0ffe7f1a7
Create Date: 2024-01-20 16:33:51.161701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73df300922c'
down_revision: Union[str, None] = 'e6f0ffe7f1a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('is_canceled', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sitter_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sitter_profile_id'], ['sitterprofiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Bookings_id'), 'Bookings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Bookings_id'), table_name='Bookings')
    op.drop_table('Bookings')
    # ### end Alembic commands ###
