"""added first and last name

Revision ID: e6f0ffe7f1a7
Revises: 4811b440f0f4
Create Date: 2024-01-20 15:18:50.769460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f0ffe7f1a7'
down_revision: Union[str, None] = '4811b440f0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sitterprofiles', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('sitterprofiles', sa.Column('last_name', sa.String(), nullable=True))
    op.alter_column('sitterprofiles', 'hourly_rate_euro',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('sitterprofiles', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sitterprofiles', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('sitterprofiles', 'hourly_rate_euro',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('sitterprofiles', 'last_name')
    op.drop_column('sitterprofiles', 'first_name')
    # ### end Alembic commands ###
